# Constantes générales
APP_NAME = "Alder SAV"
APP_VERSION = "1.0.0"
APP_DESCRIPTION = "Logiciel de gestion des retours produits"
APP_AUTHOR = "Alder"
APP_EMAIL = "sav@alder.fr"
APP_WEBSITE = "https://www.alder.fr"

# Constantes de l'interface
WINDOW_TITLE = f"{APP_NAME} v{APP_VERSION}"
WINDOW_MIN_WIDTH = 800
WINDOW_MIN_HEIGHT = 600
WINDOW_DEFAULT_WIDTH = 1200
WINDOW_DEFAULT_HEIGHT = 800

# Constantes de la base de données
DB_VERSION = "1.0"
DB_ENCODING = "utf-8"
DB_TIMEOUT = 30
DB_ISOLATION_LEVEL = "READ COMMITTED"

# Constantes des FRP
FRP_STATUS_NEW = "Nouveau"
FRP_STATUS_IN_PROGRESS = "En cours"
FRP_STATUS_WAITING = "En attente"
FRP_STATUS_RESOLVED = "Résolu"
FRP_STATUS_CANCELLED = "Annulé"

FRP_TYPE_RETURN = "Retour"
FRP_TYPE_CLAIM = "Réclamation"
FRP_TYPE_WARRANTY = "Garantie"
FRP_TYPE_OTHER = "Autre"

FRP_PRIORITY_LOW = "Basse"
FRP_PRIORITY_MEDIUM = "Moyenne"
FRP_PRIORITY_HIGH = "Haute"
FRP_PRIORITY_URGENT = "Urgente"

# Constantes des clients
CLIENT_TYPE_INDIVIDUAL = "Particulier"
CLIENT_TYPE_COMPANY = "Entreprise"
CLIENT_TYPE_ASSOCIATION = "Association"
CLIENT_TYPE_PUBLIC = "Public"

CLIENT_STATUS_ACTIVE = "Actif"
CLIENT_STATUS_INACTIVE = "Inactif"
CLIENT_STATUS_BLOCKED = "Bloqué"

# Constantes des fournisseurs
SUPPLIER_STATUS_ACTIVE = "Actif"
SUPPLIER_STATUS_INACTIVE = "Inactif"
SUPPLIER_STATUS_BLOCKED = "Bloqué"

# Constantes des transporteurs
CARRIER_STATUS_ACTIVE = "Actif"
CARRIER_STATUS_INACTIVE = "Inactif"
CARRIER_STATUS_BLOCKED = "Bloqué"

# Constantes des documents
DOCUMENT_TYPE_INVOICE = "Facture"
DOCUMENT_TYPE_DELIVERY = "Bon de livraison"
DOCUMENT_TYPE_RETURN = "Bon de retour"
DOCUMENT_TYPE_CLAIM = "Réclamation"
DOCUMENT_TYPE_WARRANTY = "Garantie"
DOCUMENT_TYPE_OTHER = "Autre"

DOCUMENT_STATUS_DRAFT = "Brouillon"
DOCUMENT_STATUS_VALIDATED = "Validé"
DOCUMENT_STATUS_CANCELLED = "Annulé"

# Constantes des utilisateurs
USER_ROLE_ADMIN = "admin"
USER_ROLE_MANAGER = "manager"
USER_ROLE_OPERATOR = "operator"
USER_ROLE_VIEWER = "viewer"

USER_STATUS_ACTIVE = "Actif"
USER_STATUS_INACTIVE = "Inactif"
USER_STATUS_BLOCKED = "Bloqué"

# Constantes des permissions
PERMISSION_MANAGE_USERS = "manage_users"
PERMISSION_MANAGE_FRP = "manage_frp"
PERMISSION_MANAGE_CLIENTS = "manage_clients"
PERMISSION_VIEW_STATISTICS = "view_statistics"
PERMISSION_EXPORT_DATA = "export_data"
PERMISSION_MANAGE_BACKUPS = "manage_backups"

# Constantes des notifications
NOTIFICATION_TYPE_FRP_CREATION = "frp_creation"
NOTIFICATION_TYPE_STATUS_CHANGE = "status_change"
NOTIFICATION_TYPE_DELAY = "delay"
NOTIFICATION_TYPE_DAILY_SUMMARY = "daily_summary"
NOTIFICATION_TYPE_WEEKLY_REPORT = "weekly_report"

# Constantes des exports
EXPORT_FORMAT_EXCEL = "xlsx"
EXPORT_FORMAT_PDF = "pdf"
EXPORT_FORMAT_CSV = "csv"
EXPORT_FORMAT_JSON = "json"

# Constantes des rapports
REPORT_TYPE_DAILY = "daily"
REPORT_TYPE_WEEKLY = "weekly"
REPORT_TYPE_MONTHLY = "monthly"
REPORT_TYPE_YEARLY = "yearly"
REPORT_TYPE_CUSTOM = "custom"

# Constantes des sauvegardes
BACKUP_TYPE_FULL = "full"
BACKUP_TYPE_INCREMENTAL = "incremental"
BACKUP_TYPE_DIFFERENTIAL = "differential"

# Constantes des archives
ARCHIVE_TYPE_FRP = "frp"
ARCHIVE_TYPE_CLIENT = "client"
ARCHIVE_TYPE_SUPPLIER = "supplier"
ARCHIVE_TYPE_CARRIER = "carrier"

# Constantes des statistiques
STATS_PERIOD_DAY = "day"
STATS_PERIOD_WEEK = "week"
STATS_PERIOD_MONTH = "month"
STATS_PERIOD_YEAR = "year"
STATS_PERIOD_CUSTOM = "custom"

# Constantes des graphiques
CHART_TYPE_BAR = "bar"
CHART_TYPE_LINE = "line"
CHART_TYPE_PIE = "pie"
CHART_TYPE_DOUGHNUT = "doughnut"
CHART_TYPE_RADAR = "radar"

# Constantes des couleurs
COLOR_PRIMARY = "#1f77b4"  # bleu
COLOR_SECONDARY = "#ff7f0e"  # orange
COLOR_SUCCESS = "#2ca02c"  # vert
COLOR_DANGER = "#d62728"  # rouge
COLOR_WARNING = "#ffc107"  # jaune
COLOR_INFO = "#17becf"  # cyan
COLOR_LIGHT = "#f8f9fa"  # gris clair
COLOR_DARK = "#343a40"  # gris foncé

# Constantes des icônes
ICON_APP = "icon.png"
ICON_LOGO = "logo.png"
ICON_FRP = "frp.png"
ICON_CLIENT = "client.png"
ICON_SUPPLIER = "supplier.png"
ICON_CARRIER = "carrier.png"
ICON_USER = "user.png"
ICON_SETTINGS = "settings.png"
ICON_HELP = "help.png"
ICON_EXIT = "exit.png"

# Constantes des templates
TEMPLATE_FRP = "frp.html"
TEMPLATE_CLIENT = "client.html"
TEMPLATE_SUPPLIER = "supplier.html"
TEMPLATE_CARRIER = "carrier.html"
TEMPLATE_REPORT = "report.html"
TEMPLATE_EMAIL = "email.html"

# Constantes des messages
MSG_WELCOME = "Bienvenue dans Alder SAV"
MSG_GOODBYE = "Au revoir"
MSG_ERROR = "Une erreur est survenue"
MSG_SUCCESS = "Opération réussie"
MSG_WARNING = "Attention"
MSG_INFO = "Information"
MSG_CONFIRM = "Confirmer"
MSG_CANCEL = "Annuler"
MSG_SAVE = "Enregistrer"
MSG_DELETE = "Supprimer"
MSG_EDIT = "Modifier"
MSG_VIEW = "Voir"
MSG_SEARCH = "Rechercher"
MSG_FILTER = "Filtrer"
MSG_SORT = "Trier"
MSG_EXPORT = "Exporter"
MSG_IMPORT = "Importer"
MSG_PRINT = "Imprimer"
MSG_HELP = "Aide"
MSG_ABOUT = "À propos"
MSG_SETTINGS = "Paramètres"
MSG_PROFILE = "Profil"
MSG_LOGOUT = "Déconnexion"
MSG_LOGIN = "Connexion"
MSG_REGISTER = "Inscription"
MSG_FORGOT_PASSWORD = "Mot de passe oublié"
MSG_RESET_PASSWORD = "Réinitialiser le mot de passe"
MSG_CHANGE_PASSWORD = "Changer le mot de passe"
MSG_UPDATE_PROFILE = "Mettre à jour le profil"
MSG_DELETE_ACCOUNT = "Supprimer le compte"
MSG_BACKUP = "Sauvegarder"
MSG_RESTORE = "Restaurer"
MSG_ARCHIVE = "Archiver"
MSG_CLEANUP = "Nettoyer"
MSG_MAINTENANCE = "Maintenance"
MSG_UPDATE = "Mettre à jour"
MSG_INSTALL = "Installer"
MSG_UNINSTALL = "Désinstaller"
MSG_CONFIGURE = "Configurer"
MSG_CUSTOMIZE = "Personnaliser"
MSG_OPTIMIZE = "Optimiser"
MSG_VALIDATE = "Valider"
MSG_VERIFY = "Vérifier"
MSG_CHECK = "Vérifier"
MSG_TEST = "Tester"
MSG_DEBUG = "Déboguer"
MSG_MONITOR = "Surveiller"
MSG_TRACK = "Suivre"
MSG_ANALYZE = "Analyser"
MSG_REPORT = "Rapporter"
MSG_NOTIFY = "Notifier"
MSG_ALERT = "Alerter"
MSG_WARN = "Avertir"
MSG_INFORM = "Informer"
MSG_CONFIRM_DELETE = "Êtes-vous sûr de vouloir supprimer ?"
MSG_CONFIRM_LOGOUT = "Êtes-vous sûr de vouloir vous déconnecter ?"
MSG_CONFIRM_EXIT = "Êtes-vous sûr de vouloir quitter ?"
MSG_CONFIRM_UPDATE = "Êtes-vous sûr de vouloir mettre à jour ?"
MSG_CONFIRM_BACKUP = "Êtes-vous sûr de vouloir sauvegarder ?"
MSG_CONFIRM_RESTORE = "Êtes-vous sûr de vouloir restaurer ?"
MSG_CONFIRM_ARCHIVE = "Êtes-vous sûr de vouloir archiver ?"
MSG_CONFIRM_CLEANUP = "Êtes-vous sûr de vouloir nettoyer ?"
MSG_CONFIRM_MAINTENANCE = "Êtes-vous sûr de vouloir effectuer la maintenance ?"
MSG_CONFIRM_UPDATE = "Êtes-vous sûr de vouloir mettre à jour ?"
MSG_CONFIRM_INSTALL = "Êtes-vous sûr de vouloir installer ?"
MSG_CONFIRM_UNINSTALL = "Êtes-vous sûr de vouloir désinstaller ?"
MSG_CONFIRM_CONFIGURE = "Êtes-vous sûr de vouloir configurer ?"
MSG_CONFIRM_CUSTOMIZE = "Êtes-vous sûr de vouloir personnaliser ?"
MSG_CONFIRM_OPTIMIZE = "Êtes-vous sûr de vouloir optimiser ?"
MSG_CONFIRM_VALIDATE = "Êtes-vous sûr de vouloir valider ?"
MSG_CONFIRM_VERIFY = "Êtes-vous sûr de vouloir vérifier ?"
MSG_CONFIRM_CHECK = "Êtes-vous sûr de vouloir vérifier ?"
MSG_CONFIRM_TEST = "Êtes-vous sûr de vouloir tester ?"
MSG_CONFIRM_DEBUG = "Êtes-vous sûr de vouloir déboguer ?"
MSG_CONFIRM_MONITOR = "Êtes-vous sûr de vouloir surveiller ?"
MSG_CONFIRM_TRACK = "Êtes-vous sûr de vouloir suivre ?"
MSG_CONFIRM_ANALYZE = "Êtes-vous sûr de vouloir analyser ?"
MSG_CONFIRM_REPORT = "Êtes-vous sûr de vouloir rapporter ?"
MSG_CONFIRM_NOTIFY = "Êtes-vous sûr de vouloir notifier ?"
MSG_CONFIRM_ALERT = "Êtes-vous sûr de vouloir alerter ?"
MSG_CONFIRM_WARN = "Êtes-vous sûr de vouloir avertir ?"
MSG_CONFIRM_INFORM = "Êtes-vous sûr de vouloir informer ?"

# Constantes des erreurs
ERROR_DATABASE = "Erreur de base de données"
ERROR_AUTHENTICATION = "Erreur d'authentification"
ERROR_AUTHORIZATION = "Erreur d'autorisation"
ERROR_VALIDATION = "Erreur de validation"
ERROR_CONFIGURATION = "Erreur de configuration"
ERROR_EXPORT = "Erreur d'export"
ERROR_IMPORT = "Erreur d'import"
ERROR_BACKUP = "Erreur de sauvegarde"
ERROR_RESTORE = "Erreur de restauration"
ERROR_NOTIFICATION = "Erreur de notification"
ERROR_DOCUMENT = "Erreur de document"
ERROR_REPORT = "Erreur de rapport"
ERROR_SCHEDULER = "Erreur de planificateur"
ERROR_CLIENT = "Erreur de client"
ERROR_FRP = "Erreur de FRP"
ERROR_SUPPLIER = "Erreur de fournisseur"
ERROR_CARRIER = "Erreur de transporteur"
ERROR_UI = "Erreur d'interface"
ERROR_NETWORK = "Erreur réseau"
ERROR_FILE = "Erreur de fichier"
ERROR_ARCHIVE = "Erreur d'archive"
ERROR_STATISTICS = "Erreur de statistiques"
ERROR_LOG = "Erreur de log"
ERROR_SECURITY = "Erreur de sécurité"
ERROR_RESOURCE = "Erreur de ressource"
ERROR_TEMPLATE = "Erreur de template"
ERROR_EMAIL = "Erreur d'email"
ERROR_QRCODE = "Erreur de QR code"
ERROR_BARCODE = "Erreur de code-barres"
ERROR_PDF = "Erreur de PDF"
ERROR_EXCEL = "Erreur d'Excel"
ERROR_IMAGE = "Erreur d'image"
ERROR_CACHE = "Erreur de cache"
ERROR_SESSION = "Erreur de session"
ERROR_MEMORY = "Erreur de mémoire"
ERROR_TIMEOUT = "Erreur de timeout"
ERROR_CONCURRENCY = "Erreur de concurrence"
ERROR_STATE = "Erreur d'état"
ERROR_VERSION = "Erreur de version"
ERROR_DEPENDENCY = "Erreur de dépendance"
ERROR_PLUGIN = "Erreur de plugin"
ERROR_UPDATE = "Erreur de mise à jour"
ERROR_MIGRATION = "Erreur de migration"
ERROR_CLEANUP = "Erreur de nettoyage"
ERROR_MAINTENANCE = "Erreur de maintenance"
ERROR_SYSTEM = "Erreur système"
ERROR_HARDWARE = "Erreur matérielle"
ERROR_SOFTWARE = "Erreur logicielle"
ERROR_INTEGRATION = "Erreur d'intégration"
ERROR_API = "Erreur d'API"
ERROR_SERVICE = "Erreur de service"
ERROR_COMPONENT = "Erreur de composant"
ERROR_MODULE = "Erreur de module"
ERROR_PACKAGE = "Erreur de package"
ERROR_LIBRARY = "Erreur de bibliothèque"
ERROR_FRAMEWORK = "Erreur de framework"
ERROR_PLATFORM = "Erreur de plateforme"
ERROR_ENVIRONMENT = "Erreur d'environnement"
ERROR_RUNTIME = "Erreur d'exécution"
ERROR_COMPILATION = "Erreur de compilation"
ERROR_SYNTAX = "Erreur de syntaxe"
ERROR_SEMANTIC = "Erreur sémantique"
ERROR_LOGIC = "Erreur de logique"
ERROR_ALGORITHM = "Erreur d'algorithme"
ERROR_DATA = "Erreur de données"
ERROR_FORMAT = "Erreur de format"
ERROR_ENCODING = "Erreur d'encodage"
ERROR_DECODING = "Erreur de décodage"
ERROR_PARSING = "Erreur de parsing"
ERROR_SERIALIZATION = "Erreur de sérialisation"
ERROR_DESERIALIZATION = "Erreur de désérialisation"
ERROR_MARSHALLING = "Erreur de marshalling"
ERROR_UNMARSHALLING = "Erreur de unmarshalling"
ERROR_CONVERSION = "Erreur de conversion"
ERROR_TRANSFORMATION = "Erreur de transformation"
ERROR_MAPPING = "Erreur de mapping"
ERROR_BINDING = "Erreur de binding"
ERROR_CONNECTION = "Erreur de connexion"
ERROR_COMMUNICATION = "Erreur de communication"
ERROR_PROTOCOL = "Erreur de protocole"
ERROR_TRANSPORT = "Erreur de transport"
ERROR_ROUTING = "Erreur de routage"
ERROR_ADDRESSING = "Erreur d'adressage"
ERROR_NAMING = "Erreur de nommage"
ERROR_RESOLUTION = "Erreur de résolution"
ERROR_DISCOVERY = "Erreur de découverte"
ERROR_REGISTRATION = "Erreur d'enregistrement"
ERROR_DEREGISTRATION = "Erreur de désenregistrement"
ERROR_SUBSCRIPTION = "Erreur d'abonnement"
ERROR_UNSUBSCRIPTION = "Erreur de désabonnement"
ERROR_PUBLICATION = "Erreur de publication"
ERROR_NOTIFICATION = "Erreur de notification"
ERROR_EVENT = "Erreur d'événement"
ERROR_MESSAGE = "Erreur de message"
ERROR_QUEUE = "Erreur de file d'attente"
ERROR_STACK = "Erreur de pile"
ERROR_BUFFER = "Erreur de buffer"
ERROR_STREAM = "Erreur de flux"
ERROR_CHANNEL = "Erreur de canal"
ERROR_PORT = "Erreur de port"
ERROR_SOCKET = "Erreur de socket"
ERROR_PIPE = "Erreur de pipe"
ERROR_SIGNAL = "Erreur de signal"
ERROR_INTERRUPT = "Erreur d'interruption"
ERROR_DEADLINE = "Erreur de deadline"
ERROR_SCHEDULE = "Erreur de planification"
ERROR_TIMING = "Erreur de timing"
ERROR_SYNCHRONIZATION = "Erreur de synchronisation"
ERROR_COORDINATION = "Erreur de coordination"
ERROR_ORCHESTRATION = "Erreur d'orchestration"
ERROR_CHOREOGRAPHY = "Erreur de chorégraphie"
ERROR_WORKFLOW = "Erreur de workflow"
ERROR_PROCESS = "Erreur de processus"
ERROR_THREAD = "Erreur de thread"
ERROR_TASK = "Erreur de tâche"
ERROR_JOB = "Erreur de job"
ERROR_BATCH = "Erreur de batch"
ERROR_TRANSACTION = "Erreur de transaction"
ERROR_OPERATION = "Erreur d'opération"
ERROR_ACTION = "Erreur d'action"
ERROR_COMMAND = "Erreur de commande"
ERROR_QUERY = "Erreur de requête"
ERROR_STATEMENT = "Erreur de statement"
ERROR_EXPRESSION = "Erreur d'expression"
ERROR_FUNCTION = "Erreur de fonction"
ERROR_METHOD = "Erreur de méthode"
ERROR_PROCEDURE = "Erreur de procédure"
ERROR_ROUTINE = "Erreur de routine"
ERROR_SCRIPT = "Erreur de script"
ERROR_PROGRAM = "Erreur de programme"
ERROR_APPLICATION = "Erreur d'application"
ERROR_SYSTEM = "Erreur système"
ERROR_PLATFORM = "Erreur de plateforme"
ERROR_ENVIRONMENT = "Erreur d'environnement"
ERROR_CONFIGURATION = "Erreur de configuration"
ERROR_SETTINGS = "Erreur de paramètres"
ERROR_OPTIONS = "Erreur d'options"
ERROR_PREFERENCES = "Erreur de préférences"
ERROR_PROFILE = "Erreur de profil"
ERROR_CONTEXT = "Erreur de contexte"
ERROR_STATE = "Erreur d'état"
ERROR_STATUS = "Erreur de statut"
ERROR_CONDITION = "Erreur de condition"
ERROR_CONSTRAINT = "Erreur de contrainte"
ERROR_REQUIREMENT = "Erreur de requirement"
ERROR_RELATIONSHIP = "Erreur de relation"
ERROR_ASSOCIATION = "Erreur d'association"
ERROR_COMPOSITION = "Erreur de composition"
ERROR_AGGREGATION = "Erreur d'agrégation"
ERROR_INHERITANCE = "Erreur d'héritage"
ERROR_POLYMORPHISM = "Erreur de polymorphisme"
ERROR_ENCAPSULATION = "Erreur d'encapsulation"
ERROR_ABSTRACTION = "Erreur d'abstraction"
ERROR_INTERFACE = "Erreur d'interface"
ERROR_IMPLEMENTATION = "Erreur d'implémentation"
ERROR_DESIGN = "Erreur de design"
ERROR_ARCHITECTURE = "Erreur d'architecture"
ERROR_STRUCTURE = "Erreur de structure"
ERROR_ORGANIZATION = "Erreur d'organisation"
ERROR_LAYOUT = "Erreur de layout"
ERROR_FORMATTING = "Erreur de formatage"
ERROR_STYLING = "Erreur de style"
ERROR_THEMING = "Erreur de thème"
ERROR_BRANDING = "Erreur de branding"
ERROR_IDENTITY = "Erreur d'identité"
ERROR_AUTHENTICATION = "Erreur d'authentification"
ERROR_AUTHORIZATION = "Erreur d'autorisation"
ERROR_PERMISSION = "Erreur de permission"
ERROR_ACCESS = "Erreur d'accès"
ERROR_SECURITY = "Erreur de sécurité"
ERROR_PRIVACY = "Erreur de confidentialité"
ERROR_CONFIDENTIALITY = "Erreur de confidentialité"
ERROR_INTEGRITY = "Erreur d'intégrité"
ERROR_AVAILABILITY = "Erreur de disponibilité"
ERROR_RELIABILITY = "Erreur de fiabilité"
ERROR_DURABILITY = "Erreur de durabilité"
ERROR_MAINTAINABILITY = "Erreur de maintenabilité"
ERROR_SCALABILITY = "Erreur de scalabilité"
ERROR_PERFORMANCE = "Erreur de performance"
ERROR_EFFICIENCY = "Erreur d'efficacité"
ERROR_OPTIMIZATION = "Erreur d'optimisation"
ERROR_RESOURCE = "Erreur de ressource"
ERROR_CAPACITY = "Erreur de capacité"
ERROR_UTILIZATION = "Erreur d'utilisation"
ERROR_ALLOCATION = "Erreur d'allocation"
ERROR_DEALLOCATION = "Erreur de désallocation"
ERROR_MANAGEMENT = "Erreur de gestion"
ERROR_ADMINISTRATION = "Erreur d'administration"
ERROR_OPERATION = "Erreur d'opération"
ERROR_MAINTENANCE = "Erreur de maintenance"
ERROR_SUPPORT = "Erreur de support"
ERROR_SERVICE = "Erreur de service"
ERROR_QUALITY = "Erreur de qualité"
ERROR_COMPLIANCE = "Erreur de conformité"
ERROR_STANDARD = "Erreur de standard"
ERROR_POLICY = "Erreur de politique"
ERROR_RULE = "Erreur de règle"
ERROR_REGULATION = "Erreur de régulation"
ERROR_GOVERNANCE = "Erreur de gouvernance"
ERROR_CONTROL = "Erreur de contrôle"
ERROR_MONITORING = "Erreur de monitoring"
ERROR_SUPERVISION = "Erreur de supervision"
ERROR_OVERSIGHT = "Erreur de supervision"
ERROR_AUDIT = "Erreur d'audit"
ERROR_INSPECTION = "Erreur d'inspection"
ERROR_VERIFICATION = "Erreur de vérification"
ERROR_VALIDATION = "Erreur de validation"
ERROR_CERTIFICATION = "Erreur de certification"
ERROR_ACCREDITATION = "Erreur d'accréditation"
ERROR_LICENSING = "Erreur de licence"
ERROR_REGISTRATION = "Erreur d'enregistrement"
ERROR_ENROLLMENT = "Erreur d'inscription"
ERROR_SUBSCRIPTION = "Erreur d'abonnement"
ERROR_MEMBERSHIP = "Erreur d'adhésion"
ERROR_AFFILIATION = "Erreur d'affiliation"
ERROR_ASSOCIATION = "Erreur d'association"
ERROR_PARTNERSHIP = "Erreur de partenariat"
ERROR_COLLABORATION = "Erreur de collaboration"
ERROR_COOPERATION = "Erreur de coopération"
ERROR_COORDINATION = "Erreur de coordination"
ERROR_INTEGRATION = "Erreur d'intégration"
ERROR_INTEROPERABILITY = "Erreur d'interopérabilité"
ERROR_COMPATIBILITY = "Erreur de compatibilité"
ERROR_PORTABILITY = "Erreur de portabilité"
ERROR_ADAPTABILITY = "Erreur d'adaptabilité"
ERROR_FLEXIBILITY = "Erreur de flexibilité"
ERROR_EXTENSIBILITY = "Erreur d'extensibilité"
ERROR_MODIFIABILITY = "Erreur de modifiabilité"
ERROR_CUSTOMIZABILITY = "Erreur de personnalisation"
ERROR_CONFIGURABILITY = "Erreur de configuration" 